import { createLocalFontProcessor } from '@unocss/preset-web-fonts/local'
import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetWebFonts,
  presetWind4,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

export default defineConfig({
  // Safelist icons used in JS/TS data objects (bound via :class)
  // UnoCSS cannot detect these through static analysis
  safelist: [
    // Products (constants/products.ts)
    'i-carbon-gas-station',
    'i-carbon-industry',
    'i-carbon-solar-panel',
    'i-carbon-fire',
    'i-carbon-flash',
    // Product color map classes (dynamic bg/text/bgLight in products showcase/pages)
    'bg-jetspan-yellow',
    'text-jetspan-black',
    'bg-jetspan-yellow/20',
    'bg-jetspan-green',
    'text-white',
    'bg-jetspan-green/20',
    'bg-jetspan-blue',
    'bg-jetspan-blue/20',
    'bg-jetspan-teal',
    'bg-jetspan-teal/20',
    'bg-jetspan-amber',
    'bg-jetspan-amber/20',
    'bg-jetspan-orange',
    'bg-jetspan-orange/20',
    // Icon text colors (WhyChooseUs, About values — dynamic :class)
    'text-jetspan-yellow',
    'text-jetspan-green',
    'text-jetspan-blue',
    'text-jetspan-teal',
    'text-jetspan-amber',
    'text-jetspan-orange',
    // Group-hover background variants (icon circle hover state)
    'group-hover:bg-jetspan-yellow',
    'group-hover:bg-jetspan-green',
    'group-hover:bg-jetspan-blue',
    'group-hover:bg-jetspan-teal',
    'group-hover:bg-jetspan-amber',
    'group-hover:bg-jetspan-orange',
    // Group-hover text variants (icon hover text color)
    'group-hover:text-white',
    'group-hover:text-jetspan-black',
    // Solar ProductShowcase (dynamic colorMap classes)
    'bg-jetspan-teal/10',
    'bg-jetspan-blue/10',
    'bg-jetspan-amber/10',
    'hover:border-jetspan-teal/50',
    'hover:border-jetspan-blue/50',
    'hover:border-jetspan-amber/50',
    // Solar CaseStudy (dynamic step accent classes)
    'text-red-500',
    'bg-red-500/20',
    'border-red-500/30',
    'bg-red-500',
    'bg-jetspan-teal/20',
    'border-jetspan-teal/30',
    'text-green-500',
    'bg-green-500/20',
    'border-green-500/30',
    'bg-green-500',
    // Solar (LingoDecoder, CaseStudy)
    'i-carbon-settings-adjust',
    'i-carbon-battery-full',
    'i-carbon-meter',
    'i-carbon-plug',
    'i-carbon-warning',
    'i-carbon-warning-alt',
    'i-carbon-tools',
    'i-carbon-checkmark-filled',
    // Fertilizer — dynamic :class icons (Who We Work With + Products We Facilitate)
    'i-carbon-license',
    'i-carbon-building',
    'i-carbon-harbor',
    'i-carbon-enterprise',
    'i-carbon-crop-growth',
    'i-carbon-chemistry-reference',
    'i-carbon-soil-moisture',
    'i-carbon-soil-temperature',
    'i-carbon-smoke',
    'i-carbon-cube',
    'i-carbon-test-tool',
    'i-carbon-sprout',
    // Fertilizer — per-item accent colour map (dynamic :class /10 backgrounds)
    'bg-jetspan-yellow/10',
    'bg-jetspan-green/10',
    'bg-jetspan-orange/10',
    // Gas (SafetyCompliance, ApplicationGrid)
    'i-carbon-certificate-check',
    'i-carbon-pressure',
    'i-carbon-user-certification',
    'i-carbon-calendar',
    'i-carbon-phone-filled',
    'i-carbon-document-signed',
    'i-carbon-delivery-truck',
    'i-carbon-restaurant',
    'i-carbon-security',
    // Diesel (QualityPromise, en590-diesel.vue warnings/SWIFT)
    'i-carbon-chemistry',
    'i-carbon-temperature-hot',
    'i-carbon-scale',
    'i-carbon-close-filled',
    'i-carbon-money',
    'i-carbon-user-multiple',
    'i-carbon-document',
    // About page (values)
    'i-carbon-scis-transparent-supply',
    'i-carbon-trophy',
    'i-carbon-earth',
    'i-carbon-collaborate',
    // WhyChooseUs
    'i-carbon-chart-line',
    'i-carbon-sustainability',
    'i-carbon-partnership',
    'i-carbon-user-favorite',
    // Contact (contactMethods + availability)
    'i-carbon-email',
    'i-carbon-phone',
    'i-carbon-globe',
    'i-mdi-whatsapp',
    // CrossSellBanner
    'i-carbon-arrow-right',
    // Color preview page
    'i-carbon-flash',
    'i-carbon-rain-drop',
    'i-carbon-fire',
    'i-carbon-delivery',
    'i-carbon-energy-renewable',
    // Solar ProductShowcase — gallery lightbox + datasheet link
    'i-carbon-image',
    'i-carbon-close',
    'i-carbon-chevron-left',
    'i-carbon-chevron-right',
    'i-carbon-document-pdf',
  ],
  shortcuts: [
    // Buttons
    ['btn', 'px-6 py-3 rounded-lg inline-block bg-jetspan-yellow text-jetspan-black font-semibold cursor-pointer hover:bg-yellow-400 disabled:cursor-default disabled:bg-gray-400 disabled:opacity-50 transition-all duration-200'],
    ['btn-primary', 'px-6 py-3 rounded-lg inline-block bg-jetspan-yellow text-jetspan-black font-semibold cursor-pointer hover:bg-yellow-400 disabled:cursor-default disabled:bg-gray-400 disabled:opacity-50 transition-all duration-200'],
    ['btn-secondary', 'px-6 py-3 rounded-lg inline-block bg-jetspan-green text-white font-semibold cursor-pointer hover:bg-green-600 disabled:cursor-default disabled:bg-gray-400 disabled:opacity-50 transition-all duration-200'],
    ['btn-outline', 'px-6 py-3 rounded-lg inline-block border-2 border-jetspan-yellow text-jetspan-yellow font-semibold cursor-pointer hover:bg-jetspan-yellow hover:text-jetspan-black transition-all duration-200'],
    ['btn-outline-white', 'px-6 py-3 rounded-lg inline-block border-2 border-white text-white font-semibold cursor-pointer hover:bg-white hover:text-jetspan-black transition-all duration-200'],
    ['btn-whatsapp', 'px-6 py-3 rounded-lg inline-block bg-green-500 text-white font-semibold cursor-pointer hover:bg-green-600 transition-all duration-200'],
    ['icon-btn', 'inline-block cursor-pointer select-none opacity-75 transition duration-200 ease-in-out hover:opacity-100 hover:text-jetspan-yellow'],
    // Cards & Layout
    ['card', 'bg-white dark:bg-jetspan-gray-dark rounded-xl p-6 shadow-lg hover:shadow-xl transition-shadow duration-300'],
    ['section-container', 'max-w-7xl mx-auto px-4 sm:px-6 lg:px-8'],
    ['section-padding', 'py-20 md:py-32'],
    // Typography — "Industrial Art" visual language
    ['heading-display', 'font-dm-serif-display'],
    ['section-title', 'text-4xl font-bold mb-4 md:text-5xl text-jetspan-black dark:text-white font-dm-serif-display'],
    ['section-subtitle', 'text-xl text-jetspan-gray mx-auto max-w-3xl dark:text-gray-400'],
    // Hero pattern
    ['hero-gradient', 'from-jetspan-black to-jetspan-gray-dark bg-gradient-to-br'],
    ['hero-overlay', 'absolute inset-0 bg-gradient-to-t from-black/80 via-black/50 to-black/30'],
  ],
  presets: [
    presetWind4(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
    }),
    presetTypography(),
    presetWebFonts({
      fonts: {
        sans: 'Inter:400,500,600,700,800',
        serif: 'DM Serif Display',
        mono: 'DM Mono',
      },
      processors: createLocalFontProcessor(),
    }),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
  theme: {
    colors: {
      // Core brand tokens (use these everywhere)
      'jetspan-yellow': '#FBE900',
      'jetspan-green': '#61A641',
      'jetspan-gray': '#5D6973',
      'jetspan-light': '#F2F2F2',
      'jetspan-black': '#0D0D0D',
      'jetspan-gray-dark': '#2D3339',
      // Aliases for EN590 page and extended palette usage
      'jetspan-navy': '#1E3A8A',
      'jetspan-blue': '#2563EB',
      'jetspan-amber': '#F59E0B',
      'jetspan-teal': '#14B8A6',
      'jetspan-orange': '#F97316',
      // Brand color palette
      'brand': {
        yellow: {
          DEFAULT: '#FBE900',
          50: '#FFFEF0',
          100: '#FFFCE0',
          200: '#FFF9C2',
          300: '#FFF6A3',
          400: '#FFF385',
          500: '#FBE900',
          600: '#DBC800',
          700: '#B99E00',
          800: '#8C7402',
          900: '#614F01',
        },
        green: {
          DEFAULT: '#61A641',
          50: '#F2F9EF',
          100: '#E3F3DE',
          200: '#C7E7BD',
          300: '#ABDB9D',
          400: '#8FCF7C',
          500: '#61A641',
          600: '#4D8534',
          700: '#3D6728',
          800: '#2E4C1F',
          900: '#1F3215',
        },
        gray: {
          DEFAULT: '#5D6973',
          50: '#F4F5F6',
          100: '#E9EBED',
          200: '#D3D7DB',
          300: '#BDC3C9',
          400: '#9DA5AD',
          500: '#5D6973',
          600: '#4A545C',
          700: '#3D454C',
          800: '#2D3339',
          900: '#1F2226',
        },
        blue: {
          DEFAULT: '#2563EB',
          50: '#EFF6FF',
          100: '#DBEAFE',
          200: '#BFDBFE',
          300: '#93C5FD',
          400: '#60A5FA',
          500: '#2563EB',
          600: '#1D4ED8',
          700: '#1E40AF',
          800: '#1E3A8A',
          900: '#1E3A70',
        },
        orange: {
          DEFAULT: '#F97316',
          50: '#FFF7ED',
          100: '#FFEDD5',
          200: '#FED7AA',
          300: '#FDBA74',
          400: '#FB923C',
          500: '#F97316',
          600: '#EA580C',
          700: '#C2410C',
          800: '#9A3412',
          900: '#7C2D12',
        },
        teal: {
          DEFAULT: '#14B8A6',
          50: '#F0FDFA',
          100: '#CCFBF1',
          200: '#99F6E4',
          300: '#5EEAD4',
          400: '#2DD4BF',
          500: '#14B8A6',
          600: '#0D9488',
          700: '#0F766E',
          800: '#115E59',
          900: '#134E4A',
        },
        amber: {
          DEFAULT: '#F59E0B',
          50: '#FFFBEB',
          100: '#FEF3C7',
          200: '#FDE68A',
          300: '#FCD34D',
          400: '#FBBF24',
          500: '#F59E0B',
          600: '#D97706',
          700: '#B45309',
          800: '#92400E',
          900: '#78350F',
        },
        navy: {
          DEFAULT: '#1E3A8A',
          50: '#EFF6FF',
          100: '#DBEAFE',
          200: '#BFDBFE',
          300: '#93C5FD',
          400: '#60A5FA',
          500: '#3B82F6',
          600: '#2563EB',
          700: '#1D4ED8',
          800: '#1E40AF',
          900: '#1E3A8A',
        },
        light: '#F2F2F2',
        dark: '#0D0D0D',
      },
    },
  },
})
